group:
  - repo: |
      jacquindev/dotfiles
    files:
      - source: .config/starship.toml
        dest: config/starship.toml
      - source: .config/yazi/
        dest: config/yazi/
      - source: .czrc
        dest: home/.czrc
