lastupdatecheck: 0
recentrepos:
    - G:\dotfiles
startuppopupversion: 5
lastversion: 0.44.1
customcommandshistory:
    - exit
    - qa
    - q
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
