[tools]
bun = "latest"
java = "openjdk-21"
node = "lts"
"npm:czg" = "latest"
"npm:git-open" = "latest"
"npm:git-recent" = "latest"
"npm:npm-check-updates" = "latest"
"npm:npm-run-all" = "latest"

[settings]
experimental = true
